est/Controllers/SystemController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using System.Globalization;


namespace est.Controllers
{
    public class SystemController : Controller
    {

        protected System.Web.UI.HtmlControls.HtmlInputButton Submit1;

        // GET: System
        public ActionResult Inicio()
        {
            if (Session["usuario"] == null || Int32.Parse(Session["censo"].ToString()) == 1)
            {
                Response.Redirect("/Home/Index");
            }

            return View();
        }

        public ActionResult ReporteGrafico()
        {

            if (Session["usuario"] == null || Int32.Parse(Session["censo"].ToString()) == 1)
            {
                ViewBag.Title = "Reporte estadistico";
                return View();

            }
            else
            {
                ViewBag.Title = "Reporte estadistico";

                return View();
            }
        }

        public void CerrarSesion()
        {
            Session["usuario"] = null;

            Response.Redirect("/Home/Index");
        }

        public ActionResult InicioReporte()
        {
            return View();
        }

        public ActionResult Censo()
        {
            if (Session["usuario"] == null || Int32.Parse(Session["censo"].ToString()) == 1)
            {
                Response.Redirect("/Home/Index");
            }

            ViewBag.Title = "Censo";

            return View();
        }

        public ActionResult CensoFoto()
        {
            if (Session["usuario"] == null || Int32.Parse(Session["censo"].ToString()) == 1)
            {
                
                Response.Redirect("/Home/Index");
            }

            ViewBag.Title = "Censo - Foto";

            return View();
        }

        public ActionResult CensoReporte()
        {
            if (Session["usuario"] == null)
            {
                Response.Redirect("/Home/Index");
            }

            ViewBag.Title = "Censo";

            return View();
        }

        public ActionResult DevocionalDominical()
        {

            if (Session["usuario"] == null || Int32.Parse(Session["censo"].ToString()) == 1)
            {
                Response.Redirect("/Home/Index");
            }

            ViewBag.Title = "Devocional dominical";

            return View();
        }

        public ActionResult DevocionalDominicalReporte()
        {
            ViewBag.Title = "Devocional dominical";

            return View();
        }

        public ActionResult Vigilia()
        {

            if (Session["usuario"] == null || Int32.Parse(Session["censo"].ToString()) == 1)
            {
                Response.Redirect("/Home/Index");
            }

            ViewBag.Title = "Vigilia";

            return View();
        }

        public ActionResult VigiliaReporte()
        {
            ViewBag.Title = "Vigilia";
            return View();

        }

        public ActionResult CultoDeOracion()
        {
            if (Session["usuario"] == null || Int32.Parse(Session["censo"].ToString()) == 1)
            {
                Response.Redirect("/Home/Index");
            }

            ViewBag.Title = "Culto de oración";

            return View();
        }

        public ActionResult CultoDeOracionReporte()
        {
            ViewBag.Title = "Culto de oración";

            return View();

        }

        public ActionResult ActividadJuvenil()
        {
            if (Session["usuario"] == null || Int32.Parse(Session["censo"].ToString()) == 1)
            {
                Response.Redirect("/Home/Index");
            }

            ViewBag.Title = "Actividad juvenil";

            return View();
        }

        public ActionResult ActividadJuvenilReporte()
        {

            ViewBag.Title = "Actividad juvenil";

            return View();
        }


        public ActionResult EscuelaBiblica()
        {
            if (Session["usuario"] == null || Int32.Parse(Session["censo"].ToString()) == 1)
            {
                Response.Redirect("/Home/Index");
            }

            ViewBag.Title = "Escuela biblica";

            return View();
        }

        public ActionResult EscuelaBiblicaReporte()
        {

            ViewBag.Title = "Escuela biblica";
            return View();

        }

        public void UploadImg()
        {
            var File1 = Request.Files[0];

            if ((File1 != null) && (File1.ContentLength > 0))
            {
                string SaveLocation = Server.MapPath("~/Content/images") + "/p_" + Request["IdPersona"] + ".jpg";
                try
                {
                    File1.SaveAs(SaveLocation);
                    Response.Redirect("/System/CensoFoto");
                }
                catch (Exception ex)
                {
                    Response.Write("Error: " + ex.Message);
                    //Note: Exception.Message returns a detailed message that describes the current exception. 
                    //For security reasons, we do not recommend that you return Exception.Message to end users in 
                    //production environments. It would be better to put a generic error message. 
                }
            }
            else
            {
                Response.Write("Please select a file to upload.");
            }
        }

        public string IngresarDevocional()
        {
            if (Session["usuario"] == null || Int32.Parse(Session["censo"].ToString()) == 1)
            {
                Response.Redirect("/Home/Index");
            }

            var serializer = new JavaScriptSerializer();

            string comentarios = Request["comentarios"];
            int adultosFueraDelTemplo = Int32.Parse(Request["adultosFueraDelTemplo"]);
            int ujieres = Int32.Parse(Request["ujieres"]);
            int adultosEnTemplo = Int32.Parse(Request["adultosEnTemplo"]);
            int jardinInfantil = Int32.Parse(Request["jardinInfantil"]);
            int primarios = Int32.Parse(Request["primarios"]);
            int principiantes = Int32.Parse(Request["principiantes"]);
            int parvulos = Int32.Parse(Request["parvulos"]);
            int responsable = 2;
            DateTime fecha = DateTime.ParseExact(Request["fecha"], "dd/MM/yyyy HH:mm:ss", CultureInfo.InvariantCulture);
            int salaCuna = Int32.Parse(Request["salaCuna"]);

            bool resultado = false;

            try
            {
                EstadisticaDBDataContext db = new EstadisticaDBDataContext();

                var Results = db.IngresarDevocional(comentarios, adultosFueraDelTemplo, ujieres, adultosEnTemplo, jardinInfantil, primarios, principiantes, parvulos, responsable, fecha, salaCuna);

                resultado = true;
            }
            catch (Exception ex)
            {
                resultado = false;
            }


            var JSON = new { success = resultado };

            string respuesta = serializer.Serialize(JSON);

            return respuesta;
        }

        public string IngresarCultoDeOracion()
        {
            if (Session["usuario"] == null || Int32.Parse(Session["censo"].ToString()) == 1)
            {
                Response.Redirect("/Home/Index");
            }

            var serializer = new JavaScriptSerializer();

            string comentarios = Request["comentarios"];
            int personasFueraDelTemplo = Int32.Parse(Request["personasFueraDelTemplo"]);
            int ujieres = Int32.Parse(Request["ujieres"]);
            int adultosEnTemplo = Int32.Parse(Request["adultosEnTemplo"]);
            int jovenesEnTemplo = Int32.Parse(Request["jovenesEnTemplo"]);
            int adolescentesEnTemplo = Int32.Parse(Request["adolescentesEnTemplo"]);
            int responsable = 2;
            int maestros = Int32.Parse(Request["maestros"]);
            int ninosEnClase = Int32.Parse(Request["ninosEnClase"]);
            int ninosEnTemplo = Int32.Parse(Request["ninosEnTemplo"]);
            DateTime fecha = DateTime.ParseExact(Request["fecha"], "dd/MM/yyyy HH:mm:ss", CultureInfo.InvariantCulture);

            bool resultado = false;

            try
            {
                EstadisticaDBDataContext db = new EstadisticaDBDataContext();

                var Results = db.IngresarCultoDeOracion(comentarios, personasFueraDelTemplo, ujieres, adultosEnTemplo, jovenesEnTemplo, adolescentesEnTemplo, maestros, ninosEnClase, ninosEnTemplo, fecha, responsable);

                resultado = true;
            }
            catch (Exception ex)
            {
                resultado = false;
            }


            var JSON = new { success = resultado };

            string respuesta = serializer.Serialize(JSON);

            return respuesta;
        }

        public string IngresarActividadJuvenil()
        {
            if (Session["usuario"] == null || Int32.Parse(Session["censo"].ToString()) == 1)
            {
                Response.Redirect("/Home/Index");
            }

            var serializer = new JavaScriptSerializer();

            string comentarios = Request["comentarios"];
            int personasFueraDelTemplo = Int32.Parse(Request["personasFueraDelTemplo"]);
            int ujieres = Int32.Parse(Request["ujieres"]);
            int adultosEnTemplo = Int32.Parse(Request["adultosEnTemplo"]);
            int jovenesEnTemplo = Int32.Parse(Request["jovenesEnTemplo"]);
            int adolescentesEnTemplo = Int32.Parse(Request["adolescentesEnTemplo"]);
            int responsable = 2;
            int maestros = Int32.Parse(Request["maestros"]);
            int ninosEnClase = Int32.Parse(Request["ninosEnClase"]);
            int ninosEnTemplo = Int32.Parse(Request["ninosEnTemplo"]);
            DateTime fecha = DateTime.ParseExact(Request["fecha"], "dd/MM/yyyy HH:mm:ss", CultureInfo.InvariantCulture);

est/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script>
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/angularjs/1.6.2/angular.min.js"></script>
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/angularjs/1.6.2/angular-route.js" ></script>
    <link href="~/Scripts/ui/jquery-ui.css" rel="stylesheet" />
    <script type="text/javascript" src="~/Scripts/ui/jquery-ui.js"></script>
    <script type="text/javascript" src="~/Scripts/main.js"></script>
    <script type="text/javascript" src="~/Scripts/sistema.js"></script>
    @Scripts.Render("~/bundles/bootstrap")
</head>
<body ng-app="Estadistica" ng-controller="SistemaController as vm">
    <script type="text/javascript">
    $(function () {
        $.datepicker.regional['es'] = {
            closeText: 'Cerrar',
            prevText: '< Ant',
            nextText: 'Sig >',
            currentText: 'Hoy',
            monthNames: ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre'],
            monthNamesShort: ['Ene', 'Feb', 'Mar', 'Abr', 'May', 'Jun', 'Jul', 'Ago', 'Sep', 'Oct', 'Nov', 'Dic'],
            dayNames: ['Domingo', 'Lunes', 'Martes', 'Miércoles', 'Jueves', 'Viernes', 'Sábado'],
            dayNamesShort: ['Dom', 'Lun', 'Mar', 'Mié', 'Juv', 'Vie', 'Sáb'],
            dayNamesMin: ['Do', 'Lu', 'Ma', 'Mi', 'Ju', 'Vi', 'Sá'],
            weekHeader: 'Sm',
            dateFormat: 'dd/mm/yy',
            firstDay: 1,
            isRTL: false,
            showMonthAfterYear: false,
            yearSuffix: ''
        };

        $.datepicker.setDefaults($.datepicker.regional['es']);

        $("#fecha").datepicker({ dateFormat: "dd mm yy", changeYear: true, changeMonth: true, });
    });
    </script>
    <script type="text/javascript">
    var patron_dui = new Array(8, 1);
    var patron_nit = new Array(4, 6, 3, 1);
    var patron_telefono = new Array(4, 4);
    var patron_fecha = new Array(4, 2, 2);
    function mascara(d, sep, pat, nums) {
        if (d.valant != d.value) {
            val = d.value
            largo = val.length
            val = val.split(sep)
            val2 = ''
            for (r = 0; r < val.length; r++) {
                val2 += val[r]
            }
            if (nums) {
                for (z = 0; z < val2.length; z++) {
                    if (isNaN(val2.charAt(z))) {
                        letra = new RegExp(val2.charAt(z), "g")
                        val2 = val2.replace(letra, "")
                    }
                }
            }
            val = ''
            val3 = new Array()
            for (s = 0; s < pat.length; s++) {
                val3[s] = val2.substring(0, pat[s])
                val2 = val2.substr(pat[s])
            }
            for (q = 0; q < val3.length; q++) {
                if (q == 0) {
                    val = val3[q]
                }
                else {
                    if (val3[q] != "") {
                        val += sep + val3[q]
                    }
                }
            }

            d.value = val
            d.valant = val
        }
    }

    function VerificarEntero(d) {
        if (isNaN(d.value)) {
            d.value = "0";
        }
    }
    </script>

    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Estadística", "Inicio", "System", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Devocionales dominicales", "DevocionalDominical", "System", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("Cultos de oración", "CultoDeOracion", "System", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("Vigilias", "Vigilia", "System", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("Actividades Juveniles", "ActividadJuvenil", "System", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("Escuela biblica", "EscuelaBiblica", "System", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("Formulario de Censo", "Censo", "System", new { area = "" }, null)</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        <br/><br />
        @RenderBody()
        <hr />
    </div>
    <footer>
        <a>Reporte estadístico</a> | <a>Calendario de actividades</a> 
    </footer>
   
    <script src="https://code.highcharts.com/highcharts.js"></script>
    <script src="https://code.highcharts.com/modules/exporting.js"></script>
</body>
</html>

est/Views/Shared/_Layout2.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700,400italic">
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/angular_material/1.1.0/angular-material.min.css">
    <style type="text/css">
        .bgc{
            background: #e3e3e3;
        }
    </style>
</head>
<body ng-app="Estadistica" ng-controller="SistemaController as vm" ng-cloak class="bgc">
    <script type="text/javascript">
        var patron_dui = new Array(8, 1);
        var patron_nit = new Array(4, 6, 3, 1);
        var patron_telefono = new Array(4, 4);
        var patron_fecha = new Array(4, 2, 2);
        function mascara(d, sep, pat, nums) {
            if (d.valant != d.value) {
                val = d.value
                largo = val.length
                val = val.split(sep)
                val2 = ''
                for (r = 0; r < val.length; r++) {
                    val2 += val[r]
                }
                if (nums) {
                    for (z = 0; z < val2.length; z++) {
                        if (isNaN(val2.charAt(z))) {
                            letra = new RegExp(val2.charAt(z), "g")
                            val2 = val2.replace(letra, "")
                        }
                    }
                }
                val = ''
                val3 = new Array()
                for (s = 0; s < pat.length; s++) {
                    val3[s] = val2.substring(0, pat[s])
                    val2 = val2.substr(pat[s])
                }
                for (q = 0; q < val3.length; q++) {
                    if (q == 0) {
                        val = val3[q]
                    }
                    else {
                        if (val3[q] != "") {
                            val += sep + val3[q]
                        }
                    }
                }

                d.value = val
                d.valant = val
            }
        }

        function VerificarEntero(d) {
            if (isNaN(d.value)) {
                d.value = "0";
            }
        }
    </script>
    <md-toolbar class="md-menu-toolbar">
        <div layout="row">
            <div>
                <h2 class="md-toolbar-tools" ng-click="vm.Redirect('/System/Inicio')">Sistema estadístico</h2>
                <md-menu-bar>
                    <md-menu>
                        <button ng-click="vm.Redirect('/System/DevocionalDominicalReporte')">
                            Devocional
                        </button>
                    </md-menu>
                    <md-menu>
                        <button ng-click="vm.Redirect('/System/CultoDeOracionReporte')">
                            Culto de oración
                        </button>
                    </md-menu>
                    <md-menu>
                        <button ng-click="vm.Redirect('/System/VigiliaReporte')">
                            Vigilia
                        </button>
                    </md-menu>
                    <md-menu>
                        <button ng-click="vm.Redirect('/System/EscuelaBiblicaReporte')">
                            Escuela bíblica
                        </button>
                    </md-menu>
                    <md-menu>
                        <button ng-click="vm.Redirect('/System/ReporteGrafico')">
                            Reporte gráfico
                        </button>
                    </md-menu>
                    <md-menu>
                        <button ng-click="vm.Redirect('/System/CensoReporte')">
                            Censo
                        </button>
                    </md-menu>
                    <md-menu>
                        <button ng-click="vm.Redirect('/System/Inicio')">
                            Volver al sistema
                        </button>
                    </md-menu>
                </md-menu-bar>
            </div>
        </div>
    </md-toolbar>
    <md-toolbar md-scroll-shrink>
        <div class="md-toolbar-tools">{{vm.Title}}</div>
    </md-toolbar>

    <div>
        @RenderBody()
    </div>
    <script type="text/javascript" src="~/Scripts/moment.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.5.5/angular.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.5.5/angular-animate.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.5.5/angular-route.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.5.5/angular-aria.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.5.5/angular-messages.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/angular_material/1.1.0/angular-material.min.js"></script>
    <script src="~/Scripts/main.js"></script>
    <script src="~/Scripts/sistema.js"></script>
    <script type="text/javascript" src="~/Scripts/main.js"></script>
    <script type="text/javascript" src="~/Scripts/sistema.js"></script>
    <script src="https://code.highcharts.com/highcharts.js"></script>
    <script src="https://code.highcharts.com/modules/exporting.js"></script>
</body>
</html>

est/Views/Shared/_Layout3.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700,400italic">
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/angular_material/1.1.0/angular-material.min.css">
    <style type="text/css">
        .bgc{
            background: #e3e3e3;
        }
    </style>
</head>
<body ng-app="Estadistica" ng-controller="SistemaController as vm" ng-cloak class="bgc">
    <script type="text/javascript">
        var patron_dui = new Array(8, 1);
        var patron_nit = new Array(4, 6, 3, 1);
        var patron_telefono = new Array(4, 4);
        var patron_fecha = new Array(4, 2, 2);
        function mascara(d, sep, pat, nums) {
            if (d.valant != d.value) {
                val = d.value
                largo = val.length
                val = val.split(sep)
                val2 = ''
                for (r = 0; r < val.length; r++) {
                    val2 += val[r]
                }
                if (nums) {
                    for (z = 0; z < val2.length; z++) {
                        if (isNaN(val2.charAt(z))) {
                            letra = new RegExp(val2.charAt(z), "g")
                            val2 = val2.replace(letra, "")
                        }
                    }
                }
                val = ''
                val3 = new Array()
                for (s = 0; s < pat.length; s++) {
                    val3[s] = val2.substring(0, pat[s])
                    val2 = val2.substr(pat[s])
                }
                for (q = 0; q < val3.length; q++) {
                    if (q == 0) {
                        val = val3[q]
                    }
                    else {
                        if (val3[q] != "") {
                            val += sep + val3[q]
                        }
                    }
                }

                d.value = val
                d.valant = val
            }
        }

        function VerificarEntero(d) {
            if (isNaN(d.value)) {
                d.value = "0";
            }
        }
    </script>
    <md-toolbar class="md-menu-toolbar">
        <div layout="row">
            <div>
                <h2 class="md-toolbar-tools" ng-click="vm.Redirect('/System/Inicio')">Sistema estadístico</h2>
                <md-menu-bar>
                    <md-menu>
                        <button ng-click="vm.Redirect('/System/DevocionalDominicalReporte')">
                            Devocional
                        </button>
                    </md-menu>
                    <md-menu>
                        <button ng-click="vm.Redirect('/System/CultoDeOracionReporte')">
                            Culto de oración
                        </button>
                    </md-menu>
                    <md-menu>
                        <button ng-click="vm.Redirect('/System/VigiliaReporte')">
                            Vigilia
                        </button>
                    </md-menu>
                    <md-menu>
                        <button ng-click="vm.Redirect('/System/EscuelaBiblicaReporte')">
                            Escuela bíblica
                        </button>
                    </md-menu>
                    <md-menu>
                        <button ng-click="vm.Redirect('/System/ReporteGrafico')">
                            Reporte gráfico
                        </button>
                    </md-menu>
                    <md-menu>
                        <button ng-click="vm.Redirect('/System/Inicio')">
                            Ir al sistema
                        </button>
                    </md-menu>
                </md-menu-bar>
            </div>
        </div>
    </md-toolbar>
    <md-toolbar md-scroll-shrink>
        <div class="md-toolbar-tools">{{vm.Title}}</div>
    </md-toolbar>

    <div>
        @RenderBody()
    </div>
    <script type="text/javascript" src="~/Scripts/moment.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.5.5/angular.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.5.5/angular-animate.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.5.5/angular-route.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.5.5/angular-aria.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.5.5/angular-messages.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/angular_material/1.1.0/angular-material.min.js"></script>
    <script type="text/javascript" src="~/Scripts/main.js"></script>
    <script type="text/javascript" src="~/Scripts/sistema.js"></script>
    <script src="https://code.highcharts.com/highcharts.js"></script>
    <script src="https://code.highcharts.com/modules/exporting.js"></script>
</body>
</html>

est/Views/Shared/_Layout4.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://code.highcharts.com/highcharts.js"></script>
    <script src="https://code.highcharts.com/modules/exporting.js"></script>
    <div>
        @RenderBody()
    </div>
</body>
</html>